### ISSUE TITLE
New machine suggestion: Grinder

### ISSUE THREAD

**Issue by piecubed** [Terumoc/terumet#12]
What if you added a terumet grinder?

**Comment by CubicMelon** [comment]
Any particular purpose of grinding in mind?

For doubling (or even tripling) of ores there is the Crystallizer, but if there's other uses (turning cobblestone into gravel/sand?) I'd be happy to consider it.

**Comment by piecubed** [comment]
Yeah, turning cobble to gravel, and basicly the use of grinders from technic... but without grinding lumps.  And, for the crystallizer, does the speed upgrade even apply?  Because i have one wiht the speed upgrade, and it is still super slow.  Maybe make the crystallizer antad faster...

**Comment by CubicMelon** [comment]
I'll definitely consider a grinder for that sort of thing at some point, why not!

For the crystallizer the speed upgrade halves the time required. per item. However, using the tripling upgrade also triples the time required, so speed upgrade + tripling => 1.5x longer than just doubling.

**Thanks for the feedback** about the speed though. Looking back, the time of 10 seconds base time for the crystallizer is a bit steep, so as of the next upcoming version the default will be 6 seconds base time. 
New values with 6 second base time in options.lua:
No upgrades: 6 sec. doubling.
With speed upgrade only: 3 sec. doubling,
With tripling upgrade only: 18 sec. tripling.
With tripling + speed upgrade: 9 seconds tripling.

However, you are more than welcome to change the speed in your current game, i[t's the option PROCESS_TIME under terumet.options.vulcan in the mod's options.lua](https://github.com/Terumoc/terumet/blob/0915b10514cfde8c3669c5fc33eb19e90915a765/terumet/options.lua#L196)

**Comment by piecubed** [comment]
Also, i will be gone next few days, so i wont asnwer any questions.  And, one more thing, make sure you can use tubelib with the grinder...

**Comment by CubicMelon** [comment]
The **Expansion Crusher** is now available in the current repo version and will be in the coming 2.2 release.
