### ISSUE TITLE
unknown items in biomatter recipes

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#29]
This is low priority and low impact. I am seeing "unknown items" multiple times as the source of biomatter on our server, namely dryplants:grass, bushes:BushLeaves1, bushes:BushLeaves2, vines:vines. I assume this is because checks are not being made to see if these mods are installed before the recipes are added. Possibly other recipes use unknown items in other mod configurations.

**Comment by CubicMelon** [comment]
Yup, these recipes were being put in regardless of whether the related mods were installed; I forgot they would show up in unified_inventory recipes regardless. That's what I get for being lazy and just shoving those in on my own server without thinking it through.
