### ISSUE TITLE
crash due to config parameter names changing

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#30]
This is very much my fault for updating to the most recent commit on github during some major changes, but two machines will currently crash our server when in use, without ad-hoc code changes I made.

For the crusher, "opts.COOK_HUPS" should probably be "opts.HEAT_HUPS".

For the lava melter, "opts.COOK_HUPS" should probably be "opts.MELT_TIME"

**Comment by CubicMelon** [comment]
Ugh, sorry about that. I haven't had a chance to test every machine since doing a bunch of changes.

Thanks for being willing to try out the new updates though, and for reporting these specific issues, I appreciate it.
