### ISSUE TITLE
Enhancement: terumet armor balancing

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#32]
The terumet armor looks awesome, but compared to diamond armor, or mithril armor from moreores, is very weak and heavy. 

I have compiled a table of values for reference:

| | helmet      |       |      |      | chest  |       |      |      | leggings |       |      |      | boots  |       |      |      | shield |       |      |      | enhanced shield |       |      |      | 
|-------------|-------|------|------|--------|-------|------|------|----------|-------|------|------|--------|-------|------|------|--------|-------|------|------|-----------------|-------|------|------|--------| 
|             | level | heal | use  | weight | level | heal | use  | weight   | level | heal | use  | weight | level | heal | use  | weight | level | heal | use  | weight          | level | heal | use  | weight | 
| wood        | 4.5   | 0    | 2000 | 0      | 9     | 0    | 2000 | 0        | 9     | 0    | 2000 | 0      | 4.5   | 0    | 2000 | 0      | 4.5   | 0    | 2000 | 0               | 7.2   | 0    | 2000 | 0      | 
| cactus      | 4.5   | 0    | 1000 | 0      | 9     | 0    | 1000 | 0        | 9     | 0    | 1000 | 0      | 4.5   | 0    | 1000 | 0      | 4.5   | 0    | 1000 | 0               | 7.2   | 0    | 1000 | 0      | 
| steel       | 9     | 0    | 800  | 1      | 13.5  | 0    | 800  | 4        | 13.5  | 0    | 800  | 3      | 9     | 0    | 800  | 1      | 9     | 0    | 800  | 3               |       |      |      |        | 
| bronze      | 9     | 6    | 400  | 1      | 13.5  | 6    | 400  | 4        | 13.5  | 6    | 400  | 3      | 9     | 6    | 400  | 1      | 9     | 6    | 400  | 3               |       |      |      |        | 
| gold        | 9     | 6    | 300  | 2      | 13.5  | 6    | 300  | 5        | 13.5  | 6    | 300  | 4      | 9     | 6    | 300  | 2      | 9     | 6    | 300  | 4               |       |      |      |        | 
| diamond     | 13.5  | 12   | 200  | 0      | 18    | 12   | 200  | 0        | 18    | 12   | 200  | 0      | 13.5  | 12   | 200  | 0      | 13.5  | 12   | 200  | 0               |       |      |      |        | 
| mithril     | 13.5  | 12   | 100  | 0      | 18    | 12   | 100  | 0        | 18    | 12   | 100  | 0      | 13.5  | 12   | 100  | 0      | 13.5  | 12   | 100  | 0               |       |      |      |        | 
| terutin     | 2.7   | 3    | 500  | -2     | 4.5   | 3    | 500  | -2       | 4.5   | 3    | 500  | -2     | 2.7   | 3    | 500  | -2     |       |      |      |                 |       |      |      |        | 
| terucopper  | 3.6   | 2    | 1200 | 0      | 5.4   | 2    | 1200 | 0        | 5.4   | 2    | 1200 | 0      | 3.6   | 2    | 1200 | 0      |       |      |      |                 |       |      |      |        | 
| terusteel   | 8.1   | 0    | 800  | 7      | 12.6  | 0    | 800  | 7        | 12.6  | 0    | 800  | 7      | 8.1   | 0    | 800  | 7      |       |      |      |                 |       |      |      |        | 
| teruchalcum | 6.3   | 4    | 1500 | 4      | 9.9   | 4    | 1500 | 4        | 9.9   | 4    | 1500 | 4      | 6.3   | 4    | 1500 | 4      |       |      |      |                 |       |      |      |        | 
| terugold    | 1.8   | 10   | 300  | 5      | 2.7   | 10   | 300  | 5        | 2.7   | 10   | 300  | 5      | 1.8   | 10   | 300  | 5      |       |      |      |                 |       |      |      |        | 
| coreglass   | 5.4   | 6    | 600  | 3      | 12.6  | 6    | 600  | 3        | 12.6  | 6    | 600  | 3      | 5.4   | 6    | 600  | 3      |       |      |      |                 |       |      |      |        | 
| vulcansuit  | 9     | 8    | 2000 | -5     | 13.5  | 8    | 2000 | -5       | 13.5  | 8    | 2000 | -5     | 9     | 8    | 2000 | -5     |       |      |      |                 |       |      |      |        | 

I don't know if it's intentionally far inferior, but as of this moment, there's little reason to make any of this armor except for decoration, with the exception of the negative weight armors (terutin and vulcansuit), as they confer additional benefits. 

Perhaps if the armor is not to be made stronger, it could confer additional benefits as the bracers do?

**Comment by CubicMelon** [comment]
This in invaluable feedback, thank you for taking the time to put together all of this information for me.

In reality the armor originally was balanced around having special effects, but those effects ended up being put into Bracers instead. I bumped up the stats a little to compensate but clearly by not enough.

I will be taking a close look at options for making the armor more lucrative to make and use soon.

I appreciate your efforts to make my mod better very much!

**Comment by CubicMelon** [comment]
Since this has had major work, I'll go ahead and close this issue for now. If further concerns come up, feel free to make a new issue!
