### ISSUE TITLE
Input and output upgrades not behaving sanely

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#35]
Not entirely sure what is happening here. 
1. Machines (e.g. an HT Furnace) with exclusively an input upgrade don't seem to see their input
2. Machines (e.g. an HT Furnace) with exclusively an output upgrade don't see their output, but sometimes pull input from adjacent chests (under weird circumstances).
Things seem a bit better behaved when using both at once.

**Comment by CubicMelon** [comment]
... I was so confused until I realized I used the wrong function (output vs. input) in one very important core function. Oops.

Should be fixed. Sorry about that.
