### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CubicMelon** [Terumoc/terumet#36]
Nobody (else) knows how anything works in this dumb mod, fix it someday already.

**Comment by fluxionary** [comment]
I could spend some time helping to upgrade the wiki, but I don't know if that's something you can share access with me? At least not without making me a co-owner of the mod.

**Comment by CubicMelon** [comment]
I appreciate the offer! I'll check out what I can do as far as allowing edit access when I get the chance.

**Comment by catwhisperer77** [comment]
Also happy to help upgrade the wiki!

**Comment by CubicMelon** [comment]
OK, I've offered collaborator status to you both on the repository, if I understand correctly, if you accept it, then this should give you access to editing the Wiki.

I just please ask do not use this status to push changes to the code base without asking first. Thank you very much for your help!

**Comment by fluxionary** [comment]
Understood, I will have no issue w/ that.

**Comment by catwhisperer77** [comment]
Can do, thank you!

**Comment by CubicMelon** [comment]
Let me know in this issue conversation if anything comes up. I'd be glad to help out if you need anything from me.

Anything I'd written prior is up for rewriting, correcting for the current version, or even just redoing altogether if you want. Be my guest, no hard feelings here.

**Comment by CubicMelon** [comment]
Just as a heads up: I'm thinking of overhauling many of the crafting recipes and also to have many basic elements of terumet mesh with basic_materials.

So, don't go to much effort of listing crafting recipes in the wiki, at least not yet.

**Comment by CubicMelon** [comment]
Major changes are complete, so feel free to reference recipes now that they have been updated.
