### ISSUE TITLE
Enhancement: reject useless upgrades

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#37]
One of the things I have to explain to users over and over again, is which machines can make use of which upgrades. It would be really useful if machines that can't make use of an upgrade, rejected attempts to install it.

**Comment by CubicMelon** [comment]
I tried to alleviate some of that with the new tooltip information on the upgrade items, but it's not an unfair request by any means to have completely useless upgrades be rejected.

Originally I wanted to avoid having to manually tag which upgrades were used by each machine (so it could programatically reject the useless ones) but... I can stop being lazy and just do that.

I'll check out adding it when I get the chance. Unfortunately I'm back to work this week so I can't work on stuff as frequently anymore :(

**Comment by CubicMelon** [comment]
Full implementation is complete.
