### ISSUE TITLE
Vacuum packed food tweak suggestions

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#39]
On Blocky Survival, vacuumed-packed food has become too overpowered. After discussions with some players, I have a couple of suggestions:
1. Only pack 1 food item, to make a vacuum-packed item that has 1.5x the food value. 
2. If the mod is installed, require basic_materials:plastic_sheet for the creation of any vacuum-packed food. 

Implementing either or both of these suggestions would be appreciated by different subsets of users. I personally like them both. Other users had other suggestions, but these turned out to be users that would rather that the stamina mod not be installed in the first place - they wanted to be able to be semi-creative with minimal effort. 

There's several other layers of suggestions about overpowered food that on Blocky Survival, but they aren't particularly relevant for these suggestions. The basic gist of the problem, though, is that before I intervened, it was far too easy to get food that entirely filled your stamina bar (or health bar, if you don't have something like the stamina mod installed). My changes were mainly to lower the base stamina/health value of most food. Some players, however, opined that my change were too much for players who are just starting out on the server and don't have regular food supplies. If vacuum-packing was 1 per 1.5x instead of 2 per 3x, this would probably make most players happy enough. 

I have a couple of other ideas for balancing food.
1. If this change is implemented, I will double my current food values for all items (see below)
2. I will try to introduce a mod that causes non-vacuum-packed food to "decay" over time - basically, by eating away at the items in a player's inventory. I don't see any reason why such a mod should be dependent on terumetal, though. Other shelf-stable looking food will probably be safe as well.

If you want to see the values for food I have defined, you can look here:
https://github.com/obl3pplifp/minetest-bls_overrides/blob/master/hunger_overrides.lua

**Comment by CubicMelon** [comment]
I'll definitely think about this, the solutions you've offered are pretty good. 

Modifying 1 food -> 1.5x effectiveness is simple enough.

Currently the vacuum oven isn't made to accept multiple items at once (really only the alloy smelter is) so I'd have to think how to implement using plastic sheets as well. That makes a lot of sense though.

I'll look into implementing these ideas when I get the chance :>


I also do like the idea of food normally decaying, giving an extra reason to want to prepare or preserve it in some way whether with terumetal's vacuum packing or another manner. Of course as you say this would be a seperate mod's work. I'd be more than happy to implement working with it with the packed food.

**Comment by CubicMelon** [comment]
added options for the numbers related to vac food, will be looking into adding plastic as a material too soon
