### ISSUE TITLE
v3.2 basic_materials integration / recipe changes feedback

### ISSUE THREAD

**Issue by CubicMelon** [Terumoc/terumet#43]
Please provide any feedback about the major recipe changes and integration with basic_materials recently here. Thank you!

**Comment by fluxionary** [comment]
So far, so good. I've heard no complaints.

**Comment by CubicMelon** [comment]
Great! I've been busy, but I want to look into making plastic sheets part of food vacuum packing soon.

**Comment by CubicMelon** [comment]
Since nothing seems to be an issue, I'll close this.
