### ISSUE TITLE
README.md outdated

### ISSUE THREAD

**Issue by catwhisperer77** [Terumoc/terumet#45]
It was brought to my attention that the README basic docs still refers to things like heated thermese blocks. I'll try to submit a PR to update it sometime this week, if no one gets around to fixing it (or if we're doing away with documentation in README entirely and just linking to the Wiki).

**Comment by CubicMelon** [comment]
Good point. I had the introduction in the README mostly for when the main audience for the mod was on the Minetest forum. Now it's kind of outdated and it probably would be best to move over to the wiki mainly, and just leave the README for installation instructions and links to the changelog, wiki, etc.

**Comment by CubicMelon** [comment]
Oh and feel free to update it yourself, I appreciate the help!

**Comment by catwhisperer77** [comment]
Ok - I might put up a Tutorial page on the wiki (probably covering up to around how to first start up an alloy smelter, since bootstrapping with a lava bucket isn't immediately obvious? and then possibly a kind of "priorities list" for a sustainable Terumet setup)

**Comment by CubicMelon** [comment]
FYI: You can now also bootstrap with a basic copper battery now too, heated in a furnace.
