### ISSUE TITLE
Enhancement: lava heater

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#46]
Lava buckets are great for bootstrapping a terumet setup, but the heat potential of large amounts of lava generally goes wasted when people move beyond basic setups. I propose a new kind of heater, the lava heater, which is mainly just a big fluid tank that can store multiple buckets of lava (and can also process lava source blocks).

**Comment by akozlovskiy119** [comment]
Isn't that what Furnace Heater is for? Maybe just increase its storage inventory space?
Also you can put lava buckets in Thermoboxes and Thermal Distributors, although they too have only one fuel slot.

**Comment by fluxionary** [comment]
Oh, you can put lava buckets into the furnace heater? maybe i missed that. If so, never mind this.
