### ISSUE TITLE
[mt 5.2] UI flickering

### ISSUE THREAD

**Issue by CubicMelon** [Terumoc/terumet#60]
Thought I'd check if terumet was still working with the newest version, so I compiled MT 5.2 and gave it a quick test.

I'm not sure if this is a minetest 5.2 issue on all formspecs but it looks like the last-drawn image on a button on machine interface formspecs flickers annoyingly with updates in 5.2

Note to self for later if/when I spend time trying to fix it: If there isn't a proper fix, maybe including a dummy/invisible extra button at the end of every formspec would fix it?

**Comment by CubicMelon** [comment]
looks like a LOT of formspec changes have happened in the past few MT updates

**Comment by fluxionary** [comment]
Was this in the 5.2 release or the a post 5.2 dev version (i.e. 5.3-dev)? They started breaking a *ton* of things after 5.2 was released. If it affects the current release, then it's probably worth fixing more than if it's a dev version.

**Comment by CubicMelon** [comment]
I just double-checked (because I am terrible at keeping track of which commits I download and compile) but it is on the release version of 5.2, currently on the minetest github release page as "stable-5"

**Comment by CubicMelon** [comment]
Don't think this is an issue anymore, closing
