### ISSUE TITLE
Pushed a fix

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#61]
@Terumoc 
Just giving you a heads up that I pushed a commit that removes the ancient logic of breaking a theremse block that was put in an HT furnace. Currently, it allowed the generation of infinite mese shards. See https://github.com/BlockySurvival/issue-tracker/issues/191

Feel free to close this issue as an acknowledgement.

**Comment by CubicMelon** [comment]
oh man I totally forgot about that, thanks for taking care of it!
