### ISSUE TITLE
Machines lose in-progress items when broken

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#63]
I used to consider this just one of those "don't do that" things, but a player has been bugging me to fix it, and I think it can be done w/out too much trouble. I've been feeling better lately, so I think I'll get to this soon.

**Comment by CubicMelon** [comment]
I vaguely remember knowing this was an issue and as you said, put it into "don't do it, dummy" territory. But if you want to go to the effort to drop pre-processed items you are more than welcome to.

**Comment by fluxionary** [comment]
It turned out to be a bit more complicated than I anticipated, and other things have taken priority. I'll hopefully get back to this some day.

**Comment by CubicMelon** [comment]
Yes unfortunately machines only store the **result** in process, not what source item(s) prior; you would have to store the pre-process item or do some sort of reverse-lookup on the recipe to determine what item(s) a machine was processing which is not trivial as far as I can remember.
