### ISSUE TITLE
Output upgrade: Full output will cause machine to become permanently blocked (fixed)

### ISSUE THREAD

**Issue by oversword** [Terumoc/terumet#66]
Already fixed, just documenting

When using the "External Output Upgrade" alone, with neither the input upgrade or the input/output upgrade, the machine will become permanently blocked if the output chest becomes full. This can be remedied by interacting with the machine, moving an upgrade or toggling heat transfer, but this is not ideal.

To test this, set up:

Machine > Chest

![image](https://user-images.githubusercontent.com/1569128/101973324-29f53f80-3c2f-11eb-9742-c3bc8137c183.png)

The machine should:
* Have an output
* Be equipped with the "External Output Upgrade"
* NOT be equipped with the "External Input Upgrade"
* NOT be equipped with the "External Input / Output Upgrade"
* Process some material

I chose the high-temp furnace processing sand into glass, I also equipped it with an infinite heat upgrade and a speed upgrade for testing purposes.

![image](https://user-images.githubusercontent.com/1569128/101973339-47c2a480-3c2f-11eb-8309-a20177ac984f.png)

To replicate:
* fill the output chest with something, it's better to use a small chest for this reason.
* put material that can be processed into the input of the machine
* wait until an item has been processed and you see the "no output space" message
* remove a stack / item from the output chest
Notice the machine does not put the item-in-waiting into the output chest even though there is space.

This is actually not an issue on alloy smelters, which seem to have the correct logic.

This bug is not present when using the input or input / output upgrades, if you perform the test with those equipped then the item-in-waiting will be put into the output chest and the processing will continue properly.

**Comment by CubicMelon** [comment]
thanks for the fix!
