### ISSUE TITLE
Input Upgrade: Items can be shift-clicked into the input inventory (fixed)

### ISSUE THREAD

**Issue by oversword** [Terumoc/terumet#68]
Already fixed, just documenting

When the "External Input Upgrade", or "External Input/Output Upgrade" is equipped, a player can put items into the machine input inventory (not the external storage, the internal storage) by holding shift and clicking a stack. The user cannot get these items out without first removing the input upgrade.

When the user does this is appears as if the items have vanished, and there is no way for them to know where they have gone.

To replicate:
* Place down any machine with an input inventory
* Equip an "External Input Upgrade"
* Find another item in your inventory
* Hold shift and click it
* Remove the input upgrade
Notice that item you shift-clicked is in the input inventory

**Comment by CubicMelon** [comment]
thanks!
