### ISSUE TITLE
ContentDB

### ISSUE THREAD

**Issue by ExeVirus** [Terumoc/terumet#70]
Hello, could you please put this mod on ContentDB for more players to find. It's a great mod and deserves more attention.

**Comment by MidnightPhantom** [comment]
Well, he is not adding it but yes I can try a modpack version if possible keeping special mods in this modpack. So

**Comment by ExeVirus** [comment]
No, don't go that route until we have to, the moderators don't like when people typically do that, because eventually the mod creator does get around to it, haha.

**Comment by MidnightPhantom** [comment]
I will ask for their permission like you have the cooltrees modpack
